[[CoolProp]]
arch = "aarch64"
git-tree-sha1 = "60697c8599cc6c293d2041fae6127cf79d169d1d"
os = "macos"

    [[CoolProp.download]]
    sha256 = "f9e7db964150ad4491b8b19292d8597b581e1a7431d5f730822ee0ce5f496220"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.aarch64-apple-darwin.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b86d3db709834388be79b35695bb9deee2b86114"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "fbebfb98ab304fa9c6a0550dc096e500a7a85beef1fbf5711748f74f6c97f614"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.aarch64-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09585de5f7c08dbef31426cd83774374326e1cad"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "b901f08eecb0b82c8abee1ba3aa292ad3e20b67d8f061f325fc997418dc4ea0d"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "942ba546012c09f190bee5c8ee7c220900d4585d"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "4cef905a51fa75aaed34999e9c9c89025e5021abc14bd43a436d33aff7af194a"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.aarch64-linux-musl-cxx03.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89a0204df25372929a5ae66246b79085c86794f4"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "9f301eeb570d5eeb1d5008f988d605b2950e8e3964fe94d58d279ed0a096cdf5"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3a69638b8637296ac83f33a7338484053efb09d"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "8b12ac9cf83da5a48acf14316346194914f3afc220a39a1d12c5fb325ba806da"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12c382344ba8ca4df30688ad0dddeeb122a29bd8"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "a85a517d31494bcff99687f1748592673f3785487505883aeefe6ed1ae5b7174"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3dc2138a764a91f0b28fa1b1996bc3da5819d82"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "56f6101f653976dc5723f364ea0311d2c3faf7677244f848f744d210acce2172"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6de5a9ece7fc9f6671b091a52f6e7285057416c"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "110ad01d4d91a81646fb20c2b1b5ae50e616cb0873b60fda16ace8dbdc0324e8"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef522db40c08dcddc844ac37453ce72be61bfe82"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "fa6b030e85978ce69e43979231b5384b6c9db850c6b3802323974c7ae14cd2b8"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cc3db8bd965837f881fcf56219e86b35cca8fa5"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "14b9edfd814c4e26552bc83541f868c670860cbddb35edb54812afa86dc10cfd"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c57199bad08dee10686a077a2a41ab202afc37d"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "4839f51f8f04b48f656ef211a5bf76128879ad567182757bf2af41a3b1d3e0fe"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6632cdb2704c488d7617acec330830536cfdc6eb"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "2857efb152c19caa493a906352fd4a6b7cb178248affe4f3fc21d7c74fedc24e"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6efbe14ecedfbbbb2e8b8a99a9408684e6762979"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "79c908013f68ef747e3b43d55d8611885b86b4024d20a741893544671e4aaa11"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.i686-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "639bb593832e5166b08c6c842ec4be2727d2d345"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "acd7f670050c3e46ac61ea58f94eac6a697e8cc75f2873fe7e9a1a2449898a92"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.i686-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b71fe4448bf77221949eab50a8ce4710026bff2"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "97bcda78c88fbae2c4471024d3220d5315375a0bb452f9504c151ef7f4946b8b"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.i686-linux-musl-cxx03.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8d8c6dc0f709b569e030df3d5d2a553b6e59b74"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "4f7f04416503ca8870f2588c0904bc3d356b51ef89515a05f23e7fa9a2af2549"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.i686-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dafcb0884c4f67b254be9151149063e39fa2771f"
os = "windows"

    [[CoolProp.download]]
    sha256 = "8ab630c78937c6adfda24e79c4ca016fab71ed3edcb8768783a54340bdd27e52"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.i686-w64-mingw32-cxx03.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f9929f2a98e8b9420d45c4a2f2504cfcf8c4b2c"
os = "windows"

    [[CoolProp.download]]
    sha256 = "720b21b9cf4b597f2ef742dbf6110d3f201fdd6ac15c3c17378948c8ad42541f"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.i686-w64-mingw32-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
git-tree-sha1 = "682adbd1845faa3c25d6d77f3d42e94e016fe0fb"
os = "macos"

    [[CoolProp.download]]
    sha256 = "bd25a0b97022e7342af5dae693de4db263419843e55e100d117acef5ef00957c"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.x86_64-apple-darwin.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12d86077355290c1b53d96ff883602f241d18615"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "fc560150d2057869eaa230e764297836301b21c59ffe9f985952638e8234c623"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.x86_64-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e18013227c533c97b482bffd3cf8a517d6965a5"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "8126a8326c70d6fe71bb5f975be43c9e76e8572ac8ccb1505e758b12294da73d"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42c3ead0c43d85a3d0f5004ed59e102688a7c18f"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "c97e62e2c2de2f57fb70c640879b1e3e2e8f04e2339758a68ab16580200400e9"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.x86_64-linux-musl-cxx03.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6997f8c552a18d168873480270424de37eca7f1f"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "4f1a866f90d8c4dbbb2be01c3d6bdce13996e7b869707aff6292ec2f6a241c33"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
git-tree-sha1 = "ba5aadb8b4d4a6cccc710d66f13bc627dc056477"
os = "freebsd"

    [[CoolProp.download]]
    sha256 = "9aa34b4d6e5a6e8b29f145ff3b1952a7780f6f34b4571f8290ca8325a802df3c"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.x86_64-unknown-freebsd.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f78ca6c35c6b8d3c7d8ab27f29603206615612d9"
os = "windows"

    [[CoolProp.download]]
    sha256 = "06201d6ce3b2710e2c87e76fd7a01cfe9076f4d1c0b029d8d1f3de14c19c714a"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c49f8608a611ba8fe9812bae6784405792364f9"
os = "windows"

    [[CoolProp.download]]
    sha256 = "eaa851f22423119d49c17937c19ba47211212841e92fffec1d779543b29753ce"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.6.0+0/CoolProp.v6.6.0.x86_64-w64-mingw32-cxx11.tar.gz"
