[[CoolProp]]
arch = "aarch64"
git-tree-sha1 = "c3f1793b046ffd2479d41eef9410cd5936e3b1c2"
os = "macos"

    [[CoolProp.download]]
    sha256 = "ba030b1f317ba22c1144fe1783190c907b605efc92ab86e9fc34bef8aa04ea39"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.aarch64-apple-darwin.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5eb1a8675fc6f3f3ccff280a8be3ad81e3d60b64"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "7424032138fd8bfd6d189cbba538f776686b1b7291fa7b2742fcb9b6414b8efb"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.aarch64-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c437d3dceede9471066a0c023ad4b35dc344e85c"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "a655fc4effb3fd5cd850b7c4697ccb2290ab3bde344f93d3eec01896fb4c22f9"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.aarch64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b1846ed632514d8a6e80c89480e50e88160741c"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "74c601b357c65160a0a04fb0323ff2bb8c403ff29e3655e05d89397ea452adef"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.aarch64-linux-musl-cxx03.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f65b3a49c63710d7aa988baf15da23bd5cd6cfc"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "741058fd1159c22f7b8b2c05dd601502ac233799b93deb70fd34f184acdd8b0e"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.aarch64-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "aarch64"
git-tree-sha1 = "3c94682636f88b40cbc9dc6dae4ee7ec5a54ad29"
os = "freebsd"

    [[CoolProp.download]]
    sha256 = "5616a6b0a184be9dfcff49e07719443c9a8a369223be32e8babb91a46f78c47a"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.aarch64-unknown-freebsd.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dd7d0126045f71d02d535173bd6c6d2c1234ab8"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "25ff277028011025ce6fcb013b3ef634bfa4ac2ef599274749eddaa5460d087e"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a5ca1f377eb7b93a6211828cd3824fe768803f5"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "486f66b890724d569976722b653313e9e310d4044ef948abdcf8ac2f109cadd2"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6fae74ce933b0fbba3edb19e160fd267b514cbb"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "f062731906f6543fac0f2293057e3b33594acb4745d830f48da4b262676fc74a"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea86cebed29e29ee119d9885c27b34be31ba8e61"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "65a1a082d2667f531835646a08cc03f91510f232aca28ed5945355695739f045"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2628b140cb219589cf478de48bee33b57d7359c8"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "02e211cba50f3c6745bd58c122dfbb1a7bce37f6868f43b6eb405fda93a89575"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ead1bdb33fdf6ae70569cca67dc5538913ae48f4"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "cac93b48214f6af16c31b0fac2d09338ca0f32cd8733deb4ab7974d826873223"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd2f7ad576a3af722f98d5f72b9c28540d89a946"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "5976305f1c441d17a124740f56eb1532c13182c6a77b2af43e623f2af80dd8ee"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f29c434282997ca10f2258164ecca916f96dfbf3"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "181c5efa2eeeb108131af9a7a77efecedb82afed3ea9c3d21ccad5f6f3c9e1fc"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5bdbc501fed15f6503d2b4d9b3fea8d15a92647"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "82c8c175724932d60e3f61701687f4b1eee95a52d9c15d2235da63202f944313"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.i686-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b7cd99c516570d900cf91bf8abcb4e406951b0a"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "32b04b3fb7ef5fbb0ed068049b8565631558ff0a90b636e38c1cb78d073919b4"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.i686-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a855da766f80c4369ca564730c0edbfd19a1aff"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "4a97786d49baa0fd2503834cc8c1520f859fd0941ca81b051caff7d4c6dea2cb"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.i686-linux-musl-cxx03.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69d244f53b5c3327c4e28313ffedc7516dec5f5e"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "5ed935d6acead906fb75d20b266513108d6bbb8b43e90f650aab352ddac1b308"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.i686-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9f25b6631ee1403cb55d5408e346970283daefa"
os = "windows"

    [[CoolProp.download]]
    sha256 = "5f359506f816eefcbcb6a7488156398a64d92bf1eb6aa882c27abe67e40b3254"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.i686-w64-mingw32-cxx03.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a0f68650c0f0c4943157502696be9112784566e"
os = "windows"

    [[CoolProp.download]]
    sha256 = "e7865a21c60e40c08d0d8ae6b0c370d0eeb78e916db3e16be7178b856f8a7d7e"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.i686-w64-mingw32-cxx11.tar.gz"
[[CoolProp]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea0a4d07a72dcaa51ed5b79c4579b4d1c84272e2"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "4a281896c37d274e7bab8d2384913aae53772c8b37cce4ca42979f58297f61c0"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.riscv64-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cd9febf0b8f8830f44f83cc285183992aa9d6de"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "0e532ea08cbffe7e22cbcbacb1391cf8b33d58be366c5e56fff9f5591395696f"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.riscv64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
git-tree-sha1 = "4009d86769fba5b6b8e1cccdd7a74e3505841d1a"
os = "macos"

    [[CoolProp.download]]
    sha256 = "75db46b284770f3e13caaf2308b42501ac33863d543d12c4a17684ff2373fd02"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.x86_64-apple-darwin.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "628a49839acbc9595f1f567171d4385f2f32301a"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "fbd2d253921a63109db46699eee5233cc47dcfe421b9f0d592fb57414f15b6e2"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.x86_64-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed6ba1631cf81f7f354b38ebd6ecb0cb9a2605b3"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "66caad1a32909e85a6dec95269e9887edaaf422a3f197328455404833a15dab0"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.x86_64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79d12218f7f2a17b44b1791ddd9b5313d0c5ba7f"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "fd3b4babdb9c196ae93ab8cb4f898bf70f174b889a836d8e824cbf865e230789"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.x86_64-linux-musl-cxx03.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18d79d28c2f011b367493580a85ca7be8741a568"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "13328c502c0915832f315ec6fe446527a4e52829ba8bf04abeaa879e2aca654f"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.x86_64-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
git-tree-sha1 = "81f2d9ae194797a225397ffdf11d7c22ea432bdb"
os = "freebsd"

    [[CoolProp.download]]
    sha256 = "d2def4605ba1dd823809e3ac15d20dd4adc9ef970f12ee72f71725cfeb63f780"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.x86_64-unknown-freebsd.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db8ec1b38bb55fc498064a2f2e58636cc5c2c65a"
os = "windows"

    [[CoolProp.download]]
    sha256 = "f577d3c67327d734a15f423bd27a8b0af1893c58730f19f05722c824c65a912c"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cf3de9857868fbe67a1be74eda8b2687287a7cd"
os = "windows"

    [[CoolProp.download]]
    sha256 = "2719908f6cf76010e05d803dbab80070427802aa22f5713f15b8cbdeaa1df9c5"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.8.0+0/CoolProp.v6.8.0.x86_64-w64-mingw32-cxx11.tar.gz"
