[[CoolProp]]
arch = "aarch64"
git-tree-sha1 = "28e555712087353bc4869fa02b65e939246059ee"
os = "macos"

    [[CoolProp.download]]
    sha256 = "38a80045bbd86a7c69880a092dd2e0023039cb9bcd81de8ddacf0169251991a1"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.aarch64-apple-darwin.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7775dfa565d47dc571879b21e86bc428c05cf4b5"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "c9645dca3fcb6c71e46d9d56a763d7c5161700cb4b13308937aa216490c541ca"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.aarch64-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c5fa04d7a506cfd80c0432a1b5f206a0c2d8868"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "7c33caa3b5d27ba8649bcf9664ba28891e22114223980d77e16178d454e6e957"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.aarch64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5488fc3eb1149a0e1b4bc9601a19b8c41895743b"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "4d02d09b4e285f2168aaa36eeb6cba31fc887af910cfae17a2ac6c33fd61131d"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.aarch64-linux-musl-cxx03.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d4af8fede36e1df2c5ad397f24de77c616a30cd"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "99c274b1b1554436a824d0a7f35e994325af1e57cff87187b4b378bf42f8cf2e"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.aarch64-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c978ffde9e7e54f422376e45d24a56b5017c7ed2"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "3a6513aa91b42b5bc23c3d850e4989b0996b7e554296d003e6d695250fe9634c"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "666800976c7f39e31b3b7d4a9905e4201ef7e2cd"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "d7c4ae0a0b8857f6252451d85fa9864c648837ddcf0f85d066b3230beee67258"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95b28a3af6b467b30ba83de8372cc62eb5cfbfa7"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "76dc20ec89ee1d6cd09e151bbaf91334bd7f88cb04f02fc2a3b31ea50622f24b"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5577b0da74df0d52dfe736e4c342120d52e96dd1"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "bc7866b37a4b86e8ff3e09b898232c0b2c75d39604816363f0064a4a44930fc9"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59a2222c2c6d173c5595ece95aec11027ab7df68"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "93f42f5bfab46ae9c7b882b71f3999b0d6dcea82e782d283ea8bf72433f20f13"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17f285292b4bc6e5c9c96cda00837018a57645b8"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "5409b9643493f7f628c8cdb2fa49d77bec80d048227e6eb00c232c110471f7de"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd8949d90a5163f018fbdb8a9754e89d1eea0379"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "b0d486e4eec119100ab5ff0fb64b7b0aed5b8a2731a6c332050c871d139fdf08"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52f993d6e847c6c62bab43ed57892c1be9a443b0"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "0ca4495eb0e1e258f1fb41d0cb6862977273b1e778f5e687d1d1545773d5c5cd"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61c7d8bbc937ea779cd41dfbb705559aa3c21fb5"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "3b9e2b85e1a89ec832c0a903e64dd937e3f23510e4a9c3a1a1fde084c88f3696"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.i686-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0536ed630790181d3eb788656d4d16c75768242"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "08293b0c185e2256b140b3e4e070b56fbeccc080ab4a8ab88639299bd283db36"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.i686-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d39e6c758630317477abab50a8089771903bccb"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "b9c4897a3b3793bee11420f477303f77f973682cb105b60a90aac52298e0bbe1"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.i686-linux-musl-cxx03.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9f6fc15fc2a8db183958d5b857fabdbbf85f5d6"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "b10c10fc5200e54efb719ceb7363e66f0d8c21b87c11e5c4bd5f2ae3129d457a"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.i686-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3191c3a1490a369b59390fdf3668b26f96c118a7"
os = "windows"

    [[CoolProp.download]]
    sha256 = "654ee03906911959b2a801b30294c622e9e5ca1b30f63743e48c64e9b7b72abd"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.i686-w64-mingw32-cxx03.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78ca6a4a5c667a3b47c651e42f1de421e4aeda29"
os = "windows"

    [[CoolProp.download]]
    sha256 = "c0e456515240f57e2e6faf256716ee107102141331483c01c7c58b6371a77578"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.i686-w64-mingw32-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
git-tree-sha1 = "2d0712fc275e8bbc921bdb27c6f56d854c4e2df9"
os = "macos"

    [[CoolProp.download]]
    sha256 = "c98d7ef55b92f1a42861b85b039fea270121b647a0ad040a5fc19da249794fe0"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.x86_64-apple-darwin.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfccaec2639ee7e6eed6eaf794ff7bf98e5c373d"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "a3b16bc258b8497409e83b64310c4827f719120aa124e83405f8242d4fb2ee7b"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.x86_64-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "691f52d32f6b8dc6301a6fb8f6361a4b48527b14"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "21bb7a10dd5305a7438449d844b4a5f2d7bc9908ed89288ba80a6f547711e2e3"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.x86_64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1d03b3301440e3e1d7b919a18c6b909ccc5a571"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "272ed663e2567e897ce5bfe77089a9f028fb0e6e8b24109448e4897715534d03"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.x86_64-linux-musl-cxx03.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8822086580455f8f1edeff371c1f3626acf40c9e"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "5d3f2562bb87f66342d525efa5ef0cfeb3095c103750356a44ec34534dd25546"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.x86_64-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
git-tree-sha1 = "4cf1fee09b9140a732811ce54c8b762b4e26d5bb"
os = "freebsd"

    [[CoolProp.download]]
    sha256 = "f9651333b9dbcae6ddc5fb1513be44f90cda99bf87f9924a8da085f48a6c9cac"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.x86_64-unknown-freebsd.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce42f0907487f0e9295125d5ac00165374207dfe"
os = "windows"

    [[CoolProp.download]]
    sha256 = "56938147a1716f489dc5f8aaa34fa47a77e8802e9dc5435cb2304750a6988c92"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d31f86e707bc7a3eea98d4dc6787874716216a2"
os = "windows"

    [[CoolProp.download]]
    sha256 = "3e39701f813faf868ceaaf3c70217dd27b2606b716ae31b0a69029e7b97a65ce"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.5.0+0/CoolProp.v6.5.0.x86_64-w64-mingw32-cxx11.tar.gz"
