[[CoolProp]]
arch = "aarch64"
git-tree-sha1 = "38bedfb5ee26f0f9ac46cc95c577a0c2111585fe"
os = "macos"

    [[CoolProp.download]]
    sha256 = "78e0216251529bd80cbab42226940bc99b197fcffde8dadd9c3d513a20be9914"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.aarch64-apple-darwin.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8579827745ea080b254c6b1452e3136dfe4f2b27"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "317ca93a4293c2e06a62b8062e0c86851319c7990ee8b47ed04804252d74de9a"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94b7b748ef0f33c8de3ac5988354da3de7dc445f"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "be57bd9799404de35b5dc40ab6d8c152443432b89db458554dc9c806d4514048"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "aarch64"
git-tree-sha1 = "423891dcc490b9226920b49e05e4cd359be80562"
os = "freebsd"

    [[CoolProp.download]]
    sha256 = "a908a1b2fe4f7d44c83af18fd8f16f74319ddcf50f827e97c8338223dfbac8cc"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.aarch64-unknown-freebsd.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6105a6f107336fd7e531d61715f07aff744d87a0"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "b41e64373be807f50b45c9755ba4b206ba06c9405649f9ae2f4e2c32a10f8f76"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b0dff136b8be5fa0e1c2a3566f718f108fa296f"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "3fe6df273c4faa2b342e0a81797281638ed005a9a679a839cca6b3b8588dcde1"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30bc6b1f8589ea5d814248b133af96f75352fe4b"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "308f3e4b6e2abe143bc6762db48b4c76fa064770dfe7ab7e0909a595b1359cbc"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "013aab1ef547105f487f48f6f2a9d1e70525eab4"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "db9bf5498e1f4a4daefd1c6505d05011a9a058f903a00dd38cc350a228edf642"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "245d27d471e9bbc012e31abeb7e3b7b569d7cbb9"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "ace967af19c3337aaf792217e0ca1ac2669f605c1b4cfa3a529355440f1cef4f"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.i686-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c019b2554d13d5295869d192b81aa324d80d8c6"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "e8c178dbf5e9efab060027b2febd61e3ff4643049b2d371dd939af64c9621071"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.i686-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6dd4e4f87e3c0fe00726d3f677ba24019ed9c223"
os = "windows"

    [[CoolProp.download]]
    sha256 = "e06bb5bc7257c3d06c6cea37ce5252f2060f165a40fb9a2ae031518140361d73"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[CoolProp]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95d99b538000d5ff0e5ff1aa79ee98ef8149b2bf"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "d68b70d4d2579f5634e3ec97b9c6b83203700ca261e36094bcbbd666135d0f8c"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
git-tree-sha1 = "e97013d3befee820906f8d82c11365e7f21bbcc9"
os = "macos"

    [[CoolProp.download]]
    sha256 = "72e6ae99d38af2c85ca547e2f23ed83696abf3abbca8c60642c494b60efad938"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.x86_64-apple-darwin.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39167a078330fe9c2309a74e5c943e6865b09cd3"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "2cc77cf47ae8fa5a51a45b64acd3ff3363162c59310e7ea3312240709a7e1cf5"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7edb382421bd250ae2322bcff6f168eb39788aed"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "cbfac3dcf2c73f834bfc24590a6708e3eddfd3329b9801b86c0d722bdfd065a2"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
git-tree-sha1 = "8ef126253dc39bd884514d7fe5a9a4e00e1e74a2"
os = "freebsd"

    [[CoolProp.download]]
    sha256 = "e71b13464222b71c7f1335a2fc6e18a205490a8951440aa1dff650463bba1c1a"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.x86_64-unknown-freebsd.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba5b7a073a56222b7e055a16444872c01338e79b"
os = "windows"

    [[CoolProp.download]]
    sha256 = "0aacaff4731ae59e26aed1dbf2cce6b63a65e80b5c5aa8ed2b2029ab815e14c2"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v8.0.0+0/CoolProp.v8.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
