[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c675a55184d17ab81683509304fdc19bcc29f6e6"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "169a08efa9be8267bc5fcb5e6e48b879bb7969ccde79c17bade496db0ce4e8e5"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.aarch64-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3763be08839e17c0014c4228b4ff2006af16f141"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "de895581dc403b8cbabf1f85c86af3966e739a677777deee8dd02f121718a417"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.aarch64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69d5c7b04b7111a89c8baf904ea34a15ca5fb64b"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "1b5167642e0494623a50849cf21aa7c3128ebda35c3f93e952f59e6b952fcf4d"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.aarch64-linux-musl-cxx03.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf9cde9b99f804c3c049d0ab29bfb02fa91dc116"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "406f8ba66047e2edecff35461c8e56a3f709919d076a3df53f3a0348a1539e9b"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.aarch64-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6300ba46fc4b0c1f1415879083387a78f17b13e"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "583d5f43295cf244a75975fdfb996b6e6444668b002362c365db8f7c803714fe"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0b05792e9d91838a76549bb43b23fee1be09ea7"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "8d4c7b8c593ee2cb54d99f1123d1e70cf966344ec1c8ae0c816f81b56b38a2d9"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84578c8cd888a041a584a424aafe41e15ccbf5bf"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "a8d726bc95eda35a20e06b3f16ae91b2c997c9eb9a7220d55a448c4eeb785eac"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a037030264ed17dc2f97df3b3fbf12299b65c934"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "64f39bbab343d40494e766f2373a6efa7a6b4c1393ae0a76e0faefc41ef3640e"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17dfa1f76b8219fa1c65c69e961ae803e2fd9d05"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "533bfac00969e2bb1238e7a0b6092efb8e56ef24c411f7e89c84fdf3d15d508b"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.i686-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc89646e91db5b41fad7c9a5332603203ad687b3"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "6a2bcfb31acbc68cba5349e9e1d8a39e375c9fcff5f364aebeebbab1463abdaf"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.i686-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd5dc13d88a8601629d9901269aa14e34dde8006"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "2a981d791f5eb268204e90498afa1f902804575d55c2fdbaa651672b155bd4f3"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.i686-linux-musl-cxx03.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9784c30684e46e2233aefe006d80a697e359758b"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "486b7ee8bd48e7389b1036008cd71a4db293be387b55b5e13aa594f323697225"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.i686-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1be5916e84191cb8e775d15cbf621e9f753fbbfa"
os = "windows"

    [[CoolProp.download]]
    sha256 = "4eec1edd8782b094eefbbf9a229fa8e76b99dd3e74e2d67c127036717be07ede"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.i686-w64-mingw32-cxx03.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "352d9b8a9a9be4bfc3d73e43f3c0f73be90f9183"
os = "windows"

    [[CoolProp.download]]
    sha256 = "db97717ca86d169ebf9df7f3057f1a21da4926b1861705640a56c270ab0f4457"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.i686-w64-mingw32-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
git-tree-sha1 = "c5ace1b3a54c84be692b7970f540be2b7243234a"
os = "macos"

    [[CoolProp.download]]
    sha256 = "f5d321d27b33cd767238a8de781fed62e7dd45ef151fd054984121f72e33c49c"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.x86_64-apple-darwin.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "799bb2d2fa1f644cf0311128b560a857fef11de9"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "737e36b45c3414deb7ee4841b83e5028b770f491482e9f07ffe6e608542749fa"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed41009c25df95d4fd622aaab5bbf351bf92dc5d"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "c4bd730169ffd64bc749635d638999182f71b522c83cefc900e24cce4185222b"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.x86_64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fecc093e7788161acee854b5ca8047940bd984e8"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "9cc55e24eb66a0f9cd4fd13273858baacf6278786bf780d5a6baa055b38c7f31"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.x86_64-linux-musl-cxx03.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07781aa6ce89a19a43e61404c346cdead42f7874"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "5cff13b910da346bf58f370b558f130b5017bdc447f98d9e401ca2e46448d6ef"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.x86_64-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
git-tree-sha1 = "5dc31fb97b8ef5387c065b18a7141752dc04639e"
os = "freebsd"

    [[CoolProp.download]]
    sha256 = "e5a55f3dc878ae322f8842a5e83017212f830e9ff7c886467649b35a716bd41e"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.x86_64-unknown-freebsd.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c11c0d7393e0448dccb870e3aca2bcf24672180f"
os = "windows"

    [[CoolProp.download]]
    sha256 = "2b967986a4ee89c5577ca43efd741f6f3c8ddf54007600a3cb2933a904686623"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6f269ec3d5fb27bef171c873d48a609294d85ce"
os = "windows"

    [[CoolProp.download]]
    sha256 = "e94c71f829bf9692c5a3acadf28bcf2dbe7b29e758a216b4dd720f0970cb1c52"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v6.4.1+1/CoolProp.v6.4.1.x86_64-w64-mingw32-cxx11.tar.gz"
