[[CoolProp]]
arch = "aarch64"
git-tree-sha1 = "1975f8cbfd94550080fedeb2f125175897b7a590"
os = "macos"

    [[CoolProp.download]]
    sha256 = "93d9b1e7397d00d77e938e7b52cad9ee1b94a5c686ac59114dfe9b415a53c9b2"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.aarch64-apple-darwin.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1656a9ce79cc8302845324fb7ca5eb9f3e613d11"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "6d00c998b8cd19f343b026dce7a7f9dd8267df555c1b0c1d84883f6e2352bfd7"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa7dab5c4e1d629ec55139585cb6a75a39687be8"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "da6f59bfcbdc3c58340a9ed0bdfb8b12afa0b173d40faf73448b51a4fc4cd586"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "aarch64"
git-tree-sha1 = "7ab3adbb7a0980249633c3aec101a8a70dcf5ad8"
os = "freebsd"

    [[CoolProp.download]]
    sha256 = "504b65d0f2d9d2d428a56a2c054eef39e0079661edcba837e107b0aaa770de89"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.aarch64-unknown-freebsd.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97f2dff3c3f74ca6b165a5741bcaddbb90afdf33"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "e3e4558dedd56aa60a4294d61b5fb2fc02a32a06ef2378ba503bc6a6410ed715"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "232cc79d638616c91e304db0f3492966c3f40bcf"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "c679f8975001d23e9df58c6207c4ee9b3b19fbf79f1f8f84357048673269e3f0"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9150f3c85aa5c01cf26f788ab29d2760e40a74b"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "febab63d86f8ad0f016a59724ee9968a93817d499cbf156de5ca3f08a7a2cec0"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "587adc5edada0f821f63f2e53a387e487152764a"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "1f4a5898400c11be3ba6e428f15642ab0c60dac94c03adc32911f918ff7c6470"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39e0484fe587c80caa0ebe8d3e188efde97b413f"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "be01858be5506fcea44c6532d34c903a1286cdd66070e70476b11773c3cc26a4"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.i686-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8286d44e4c10c57c6720ee44a42a5453def8e81a"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "ee0c01b9f65f947fb274fdb3557168adb62536b7f6667a021dcec90635791fb7"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.i686-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6afe96c06df1fdcc52b2c70ec9eb9e71212f7ab0"
os = "windows"

    [[CoolProp.download]]
    sha256 = "58db8703dea0cdef4cc9c7fdb3088ee33146283edb6898f2da28697578b77c1f"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[CoolProp]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f4cd36ce316600515f44af3270a2e0c38d8de64"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "c12a6bc447c2222f206729e77773d58a1b44adabe396ed5640a8643d1e4f710b"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.riscv64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
git-tree-sha1 = "9d9203705268eb06f9140ad3d0de49bc197fcdfa"
os = "macos"

    [[CoolProp.download]]
    sha256 = "ee10fa068a6be27ee462e233ca0e54b5a1339bcd6475c51b7b8833d6d71fd37c"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.x86_64-apple-darwin.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0033b4c5d62a224e771358211222b0110133b204"
libc = "glibc"
os = "linux"

    [[CoolProp.download]]
    sha256 = "6c6036ef31e0ed9f1feefe5c9b9a230b14e566e6f531631f12d9d050c53d1309"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "717933ed77c5979d43db6e8aaef4987bef3d64fb"
libc = "musl"
os = "linux"

    [[CoolProp.download]]
    sha256 = "bf2cc2820137927c09feba6e7d44dfe53b7429e3ab82b606d0077002eb945df7"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[CoolProp]]
arch = "x86_64"
git-tree-sha1 = "a3e8fdc72f78d81146c8afc8f75e355ebfc7db47"
os = "freebsd"

    [[CoolProp.download]]
    sha256 = "8f23c98868d007b64745e0146941d345a1defc4018f2dd88b5575d06b3836908"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.x86_64-unknown-freebsd.tar.gz"
[[CoolProp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "903b5a870bacd5fe7c398126c02a132fe726a08d"
os = "windows"

    [[CoolProp.download]]
    sha256 = "3fecf55386d653d4d64733a79f89cb919205b42d28785677d7b188c26d560295"
    url = "https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl/releases/download/CoolProp-v7.2.0+0/CoolProp.v7.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
