# Autogenerated wrapper script for CoolProp_jll for aarch64-apple-darwin
export libcoolprop

JLLWrappers.@generate_wrapper_header("CoolProp")
JLLWrappers.@declare_library_product(libcoolprop, "@rpath/libCoolProp.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcoolprop,
        "lib/libCoolProp.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
