# Autogenerated wrapper script for CoolProp_jll for i686-w64-mingw32-cxx03
export libcoolprop

JLLWrappers.@generate_wrapper_header("CoolProp")
JLLWrappers.@declare_library_product(libcoolprop, "libCoolProp.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcoolprop,
        "bin\\libCoolProp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
